### ISSUE TITLE
Example of custom parser from `README.md` doesn't work

### ISSUE THREAD

**Issue by Pamplemousse** [GregRos/parjs#92]
I am trying to write a custom parser, following https://github.com/GregRos/parjs#creating-the-parser .

```typescript
# test.ts
import { Parjser } from "parjs";
import { ParjserBase, ParsingState } from "parjs/internal";

export function caseString<T extends string>(str: T): Parjser<T> {
	return new (class ParseString extends ParjserBase<T> {
		expecting = `message`;
		type = "string";
		_apply(ps: ParsingState): void {
      // ...
		}
	})();
}
```

but I am getting the following compilation error:

```shell
$ ts-node test.ts
node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
test.ts:5:13 - error TS2351: This expression is not constructable.
  Type 'typeof ParseString' has no construct signatures.

  5  return new (class ParseString extends ParjserBase<T> {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  6   expecting = `message`;
    ~~~~~~~~~~~~~~~~~~~~~~~~
... 
 10   }
    ~~~
 11  })();
    ~~~
test.ts:5:40 - error TS2315: Type 'ParjserBase' is not generic.

5  return new (class ParseString extends ParjserBase<T> {
                                         ~~~~~~~~~~~~~~

    at createTSError (node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (node_modules/ts-node/src/index.ts:863:19)
    at getOutput (node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Object.require.extensions.<computed> [as .ts] (node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 2351, 2315 ]
}
```

FYI, I am using the following versions:

```shell
$ ./node_modules/ts-node/dist/bin.js -vvv
ts-node v10.9.1 node_modules/ts-node
node v16.19.1
compiler v5.3.3 node_modules/typescript/lib/typescript.js
```

**Comment by Pamplemousse** [comment]
Ah, it seems that this example relies on code changes from https://github.com/GregRos/parjs/commit/a1e925bd782a714c28e1fa49ec2cb2792a80ab88, which hasn't been released (yet), so it's not available on the latest version published on `npm` (`0.16.1`).

**Comment by barona-mika-vilpas** [comment]
I started working on a release yesterday, but hit some challenges. Let's keep this open until that is resolved.

**Comment by sp3ctum** [comment]
This should now be resolved with #97
